{% set name = "qjson" %}
{% set version = "0.9.0" %}
{% set sha256 = "e812617477f3c2bb990561767a4cd8b1d3803a52018d4878da302529552610d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/flavio/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1003

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libqjson-qt5.so  # [linux]
    - test -f ${PREFIX}/lib/libqjson-qt5.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\qjson-qt5.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qjson-qt5.lib exit 1  # [win]

about:
  home: http://qjson.sourceforge.net/
  license: LGPLv2.1
  license_file: README.license
  summary: 'QJson is a qt-based library that maps JSON data to QVariant objects'
  description: |
      JSON (JavaScript Object Notation) is a lightweight data-interchange format.
      It can represents integer, real number, string, an ordered sequence of value,
      and a collection of name/value pairs.
      QJson is a Qt-based library that maps JSON data to QVariant objects and vice versa.
  doc_url: http://qjson.sourceforge.net/usage/
  dev_url: https://github.com/flavio/qjson

extra:
  recipe-maintainers:
    - ceholden
