travis:
  secure:
    BINSTAR_TOKEN: OV+FTpkxNujoxuMsKXzKGJh/RcZPhHevK0fes1KhuyPu/jUwHv7gGzfV4JkVQ/ppEGUcEdaSOraHMfctZ3SAKhpHHDC0EN1uZ9HiRtOBdYrn+g5EGnWLJhn7ghO5FKsh5LuN2bJCg2NoZeP/etaKeBFLxhpZcHiyVahxOz1sXXtoRDlgj/YfJoG85i1wGArLa6r9vtheDGI4RBjTcJPjQ73PGEFZ2cR+0cdE+BWTZOggMLllT9AxYMjIYxv55rinI/bhMg6j0evqPid2sJkYWgtWdIiGGoqcC7e7flwDkYoB4oqKt7Ddc7GbxTxH5/m7YtRSpQWfgg3WVvatuBUkbgrr427HPmeEU+asOj5cYjunNIIdtmjYiJTHF94Bk3b2syuuvpPzl4X/ArMGNiHG6bhF2USHjBLmd8LyDsai0/YmpPvoGg5tqTD1q7PUM6G9DCAIgZ4LB0d6m/P04+w8ItSEmdYvbn0CWw/XMKBxcs0Fu3WVnjtDYSs7TTbTJRjj+v4hXg9Swsq01LzgksNHUwo+bvI6ZO2sq+0vBnaeUq8Pqiktcnvz5NJHpOSnWThMN8v3wIKLbbr01O2djD3x1tcGxrDleq9EsjnLpbp0Y3+LZCDMPcM6YXxIL52b/tO7nObxJLIXLnFG1LUaBIGUKOqhIPj/6OU5KvWRZMzwbmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
